/*In the above program the programmer is creating exception object explicitly. The main method
is not responsible person to creates exception object.*/

class throwskeyword
{
public static void main(String[] args)
{
throw new ArithmeticException("we are getting Exception / by zero man");
}
}